import '../public/min-images/clock.min.png';
import '../public/min-images/face.min.png';
import '../public/min-images/girl.min.png';
import '../public/min-images/laptop-money.min.png';
import '../public/min-images/milk.min.png';
import '../public/min-images/people.min.png';
import '../public/min-images/tasks.min.png';
import '../public/min-images/zero.min.png';
import '../public/min-images/logo.min.png';